package template

const UtmAttributionData = `___INFO___

{
  "type": "MACRO",
  "id": "cvt_temp_public_id",
  "version": 1,
  "securityGroups": [],
  "displayName": "%s",
  "brand": {
    "id": "brand_dummy",
    "displayName": "sesamy",
    "thumbnail": ""
  },
  "description": "Managed by Sesamy. DO NOT EDIT.\nReads UTM attribution data (current and first-touch) from the event URL and the shared attribution cookie.",
  "containerContexts": [
    "SERVER"
  ]
}


___TEMPLATE_PARAMETERS___

[]


___SANDBOXED_JS_FOR_SERVER___

const getAllEventData = require('getAllEventData');
const getCookieValues = require('getCookieValues');
const getRequestHeader = require('getRequestHeader');
const JSON = require('JSON');
const parseUrl = require('parseUrl');

const COOKIE_NAME = 'utm_attribution';
const UTM_KEYS = ['utm_source', 'utm_medium', 'utm_campaign', 'utm_content', 'utm_term', 'utm_id'];

const eventData = getAllEventData();

// Fall back to the referer header for server-only events with no page_location
// (e.g. a purchase API call that never carried the landing-page URL).
const url = eventData.page_location || getRequestHeader('referer');
const urlParsed = url ? parseUrl(url) : null;

// 1. Parse this event's own URL for current-touch UTM values.
const current = {};
if (urlParsed) {
  UTM_KEYS.forEach((key) => {
    if (urlParsed.searchParams[key]) current[key] = urlParsed.searchParams[key];
  });
}

// 2. Read whatever the writer tag has already persisted.
// JSON.parse returns undefined (rather than throwing) on malformed input in
// the sandboxed JS runtime — try/catch is unsupported here.
const cookieRaw = getCookieValues(COOKIE_NAME)[0];
const stored = (cookieRaw && JSON.parse(cookieRaw)) || {};

// 3. Merge: current event wins for the plain utm_* keys (session/last-touch);
//    the stored initial_utm_* value wins for the initial_ keys (first-touch,
//    immutable) — falling back to the current value only if nothing was
//    ever stored (i.e. this is the user's very first hit).
const result = {};
UTM_KEYS.forEach((key) => {
  const value = current[key] || stored[key];
  if (value) result[key] = value;

  const initialKey = 'initial_' + key;
  const initialValue = stored[initialKey] || current[key];
  if (initialValue) result[initialKey] = initialValue;
});

return result;


___SERVER_PERMISSIONS___

[
  {
    "instance": {
      "key": {
        "publicId": "read_request",
        "versionId": "1"
      },
      "param": [
        {
          "key": "requestAccess",
          "value": {
            "type": 1,
            "string": "any"
          }
        },
        {
          "key": "headerAccess",
          "value": {
            "type": 1,
            "string": "any"
          }
        },
        {
          "key": "queryParameterAccess",
          "value": {
            "type": 1,
            "string": "any"
          }
        }
      ]
    },
    "isRequired": true
  },
  {
    "instance": {
      "key": {
        "publicId": "get_cookies",
        "versionId": "1"
      },
      "param": [
        {
          "key": "cookieAccess",
          "value": {
            "type": 1,
            "string": "any"
          }
        }
      ]
    },
    "isRequired": true
  },
  {
    "instance": {
      "key": {
        "publicId": "read_event_data",
        "versionId": "1"
      },
      "param": [
        {
          "key": "eventDataAccess",
          "value": {
            "type": 1,
            "string": "any"
          }
        }
      ]
    },
    "isRequired": true
  }
]


___TESTS___

scenarios: []


___NOTES___

Code generated by sesamy. DO NOT EDIT.
`
