version: "2"
run:
  go: 1.24.1
  build-tags:
    - safe
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      disabled-checks:
        - ifElseChain
        - commentFormatting
    gomoddirectives:
      replace-local: true
    gosec:
      confidence: medium
    importas:
      no-unaliased: true
    misspell:
      mode: restricted
    predeclared:
      ignore:
        - new
        - error
    revive:
      enable-all-rules: true
      rules:
        - name: line-length-limit
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: add-constant
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: function-length
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: argument-limit
          disabled: true
        - name: max-control-nesting
          disabled: true
        - name: comment-spacings
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: struct-tag
          arguments:
            - json,inline
            - yaml,squash
        - name: unhandled-error
          arguments:
            - fmt.Println
            - viper.BindPFlag
            - strings.Builder.WriteString
        - name: deep-exit
          disabled: true
        - name: if-return
          disabled: true
        - name: empty-block
          disabled: true
        - name: indent-error-flow
          disabled: true
    testifylint:
      disable:
        - float-compare
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forbidigo
          - forcetypeassert
        path: _test\.go
      - linters:
          - asasalint
        path: (.+)_test\.go
    paths:
      - bin
      - tmp
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - bin
      - tmp
      - third_party$
      - builtin$
      - examples$
