version: 2

builds:
  - binary: sesamy
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - '7'
    flags:
      - -trimpath
      - -tags=safe
    ldflags:
      - -s -w -X github.com/foomo/sesamy-cli/cmd.version={{.Version}}

release:
  prerelease: auto

archives:
  - formats: [ tar.gz ]
    format_overrides:
      - goos: windows
        formats: [ zip ]

changelog:
  use: github-native

brews:
  - repository:
      owner: foomo
      name: homebrew-tap
    caveats: "sesamy --help"
    homepage: "https://github.com/foomo/sesamy-cli"
    description: "CLI utitlity to manage Server Side Tag Management"
    test: |
      system "#{bin}/sesamy --version"

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - '{{ if eq .Prerelease "" }}foomo/sesamy:latest-amd64{{ end }}'
      - 'foomo/sesamy:{{ .Version }}-amd64'
      - '{{ if eq .Prerelease "" }}foomo/sesamy:{{ .Major }}-amd64{{ end }}'
      - '{{ if eq .Prerelease "" }}foomo/sesamy:{{ .Major }}.{{ .Minor }}-amd64{{ end }}'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=CLI utility manage infrastructure as code with helm'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation={{.GitURL}}'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/amd64'

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - '{{ if eq .Prerelease "" }}foomo/sesamy:latest-arm64{{ end }}'
      - 'foomo/sesamy:{{ .Version }}-arm64'
      - '{{ if eq .Prerelease "" }}foomo/sesamy:{{ .Major }}-arm64{{ end }}'
      - '{{ if eq .Prerelease "" }}foomo/sesamy:{{ .Major }}.{{ .Minor }}-arm64{{ end }}'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=CLI utility manage infrastructure as code with helm'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation={{.GitURL}}'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/arm64'

docker_manifests:
  # basic
  - name_template: 'foomo/sesamy:latest'
    image_templates:
      - 'foomo/sesamy:latest-amd64'
      - 'foomo/sesamy:latest-arm64'
    skip_push: auto

  - name_template: 'foomo/sesamy:{{ .Version }}'
    image_templates:
      - 'foomo/sesamy:{{ .Version }}-amd64'
      - 'foomo/sesamy:{{ .Version }}-arm64'
    skip_push: auto

  - name_template: 'foomo/sesamy:{{ .Major }}'
    image_templates:
      - 'foomo/sesamy:{{ .Major }}-amd64'
      - 'foomo/sesamy:{{ .Major }}-arm64'
    skip_push: auto

  - name_template: 'foomo/sesamy:{{ .Major }}.{{ .Minor }}'
    image_templates:
      - 'foomo/sesamy:{{ .Major }}.{{ .Minor }}-amd64'
      - 'foomo/sesamy:{{ .Major }}.{{ .Minor }}-arm64'
    skip_push: auto
