package typescript_test

import (
	"context"
	"testing"

	"github.com/foomo/sesamy-cli/internal"
	"github.com/foomo/sesamy-cli/pkg/typescript"
	_ "github.com/foomo/sesamy-go"              // force inclusion
	_ "github.com/foomo/sesamy-go/event/params" // force inclusion
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestBuiler(t *testing.T) {
	cfg := &internal.Config{
		Packages: []*internal.ConfigPackage{
			{
				Path:  "github.com/foomo/sesamy-go/event",
				Names: []string{"PageView", "AddToCart"},
			},
		},
	}
	scanner := internal.NewScanner(cfg)
	err := scanner.Scan(context.TODO())

	// structTypes, err := internal.GetStructTypes(context.TODO(), config.Packages{
	// 	{
	// 		Path: "github.com/foomo/sesamy-go/event",
	// 		Events: []string{
	// 			"PageView",
	// 			"SelectItem",
	// 			"AddToCart",
	// 		},
	// 	},
	// })
	// require.NoError(t, err)

	b := typescript.NewBuilder(scanner)
	// b.AddStructs(structTypes)
	actual, err := b.Package(context.Background(), cfg.PackagePaths())
	require.NoError(t, err)

	{
		expected := `
// Code generated by sesamy. DO NOT EDIT.
import * as github_com_foomo_sesamy_go from './github_com_foomo_sesamy_go.ts';
import { collect } from '@foomo/sesamy';

export interface AddToCart {
	name: github_com_foomo_sesamy_go.EventName;
	params: github_com_foomo_sesamy_go_event_params.AddToCart;
};

export const addToCart = (params: AddToCart) => {
	collect({ name:'add_to_cart', params });
};

export interface PageView {
	name: github_com_foomo_sesamy_go.EventName;
	params: github_com_foomo_sesamy_go_event_params.PageView;
};

export const pageView = (params: PageView) => {
	collect({ name:'page_view', params });
};

`
		if !assert.Equal(t, expected, "\n"+actual["github.com/foomo/sesamy-go/event"]) {
			t.Log("\n" + actual["github.com/foomo/sesamy-go/event"])
		}
	}

	{
		expected := `
// Code generated by sesamy. DO NOT EDIT.

export enum EventName {
	AdImpression = "ad_impression",
	AddPaymentInfo = "add_payment_info",
	AddShippingInfo = "add_shipping_info",
	AddToCart = "add_to_cart",
	AddToWishlist = "add_to_wishlit",
	BeginCheckout = "begin_checkout",
	CampaignDetails = "campaign_details",
	Click = "click",
	EarnVirtualMoney = "earn_virtual_money",
	FileDownload = "file_download",
	FormStart = "form_start",
	FormSubmit = "form_submit",
	GenerateLead = "generate_lead",
	JoinGroup = "join_group",
	LevelEnd = "level_end",
	LevelStart = "level_start",
	LevelUp = "level_up",
	Login = "login",
	PageView = "page_view",
	PostScore = "post_score",
	Purchase = "purchase",
	Refund = "refund",
	RemoveFromCart = "remove_from_cart",
	ScreenView = "screen_view",
	Scroll = "scroll",
	Search = "search",
	SelectContent = "select_content",
	SelectItem = "select_item",
	SelectPromotion = "select_promotion",
	SessionStart = "session_start",
	Share = "share",
	SignUp = "sign_up",
	SpendVirtualCurrency = "spend_virtual_currency",
	TutorialBegin = "tutorial_begin",
	TutorialComplete = "tutorial_complete",
	UnlockArchievement = "unlock_archievement",
	UserEngagement = "user_engagement",
	VideoComplete = "video_complete",
	VideoProgress = "video_progress",
	VideoStart = "video_start",
	ViewCart = "view_cart",
	ViewItem = "view_item",
	ViewItemList = "view_item_list",
	ViewPromotion = "view_promotion",
	ViewSearchResults = "view_search_results",
};
`
		if !assert.Equal(t, expected, "\n"+actual["github.com/foomo/sesamy-go"]) {
			t.Log("\n" + actual["github.com/foomo/sesamy-go"])
		}
	}
}
