package typescript_test

import (
	"context"
	"testing"

	"github.com/foomo/sesamy-cli/internal"
	"github.com/foomo/sesamy-cli/pkg/typescript"
	_ "github.com/foomo/sesamy-go"              // force inclusion
	_ "github.com/foomo/sesamy-go/event/params" // force inclusion
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestBuiler(t *testing.T) {
	cfg := &internal.LoaderConfig{
		Packages: []*internal.PackageConfig{
			{
				Path:  "github.com/foomo/sesamy-go/event",
				Types: []string{"AddToCart", "PageView"},
			},
		},
	}
	parser := internal.NewLoader(cfg)
	require.NoError(t, parser.Load(context.TODO()))

	generator := typescript.NewBuilder(parser)
	actual, err := generator.Build(context.Background())
	require.NoError(t, err)

	{
		expected := `
// Code generated by sesamy. DO NOT EDIT.
import type * as github_com_foomo_sesamy_go_event_params from './github_com_foomo_sesamy_go_event_params';
import { EventName } from './github_com_foomo_sesamy_go';
import { collect } from '@foomo/sesamy';

export const addToCart = (
	params: github_com_foomo_sesamy_go_event_params.AddToCart<github_com_foomo_sesamy_go_event_params.Item>,
) => {
	collect({
		name: EventName.AddToCart,
		params,
	});
}

export const pageView = (
	params: github_com_foomo_sesamy_go_event_params.PageView,
) => {
	collect({
		name: EventName.PageView,
		params,
	});
}
`
		if !assert.Equal(t, expected, "\n"+actual["github_com_foomo_sesamy_go_event.ts"].String()) {
			t.Log("\n" + actual["github_com_foomo_sesamy_go_event.ts"].String())
		}
	}

	{
		expected := `
// Code generated by sesamy. DO NOT EDIT.

export enum EventName {
	AdImpression = "ad_impression",
	AddPaymentInfo = "add_payment_info",
	AddShippingInfo = "add_shipping_info",
	AddToCart = "add_to_cart",
	AddToWishlist = "add_to_wishlit",
	BeginCheckout = "begin_checkout",
	CampaignDetails = "campaign_details",
	Click = "click",
	EarnVirtualMoney = "earn_virtual_money",
	FileDownload = "file_download",
	FormStart = "form_start",
	FormSubmit = "form_submit",
	GenerateLead = "generate_lead",
	JoinGroup = "join_group",
	LevelEnd = "level_end",
	LevelStart = "level_start",
	LevelUp = "level_up",
	Login = "login",
	PageView = "page_view",
	PostScore = "post_score",
	Purchase = "purchase",
	Refund = "refund",
	RemoveFromCart = "remove_from_cart",
	ScreenView = "screen_view",
	Scroll = "scroll",
	Search = "search",
	SelectContent = "select_content",
	SelectItem = "select_item",
	SelectPromotion = "select_promotion",
	SessionStart = "session_start",
	Share = "share",
	SignUp = "sign_up",
	SpendVirtualCurrency = "spend_virtual_currency",
	TutorialBegin = "tutorial_begin",
	TutorialComplete = "tutorial_complete",
	UnlockArchievement = "unlock_archievement",
	UserEngagement = "user_engagement",
	VideoComplete = "video_complete",
	VideoProgress = "video_progress",
	VideoStart = "video_start",
	ViewCart = "view_cart",
	ViewItem = "view_item",
	ViewItemList = "view_item_list",
	ViewPromotion = "view_promotion",
	ViewSearchResults = "view_search_results",
}

export interface Event<P> {
	name: EventName;
	params: P;
}
`
		if !assert.Equal(t, expected, "\n"+actual["github_com_foomo_sesamy_go.ts"].String()) {
			t.Log("\n" + actual["github_com_foomo_sesamy_go.ts"].String())
		}
	}
}
