// Code generated by tygo. DO NOT EDIT.

//////////
// source: addtocart.go

export interface AddToCart {
	currency?: string;
	value?: number /* float64 */;
	items?: (Item | undefined)[];
}

//////////
// source: item.go

export interface Item {
	affiliation?: string;
	coupon?: string;
	discount?: number /* float64 */;
	index?: number /* int */;
	item_brand?: string;
	item_category?: string;
	item_category2?: string;
	item_category3?: string;
	item_category4?: string;
	item_category5?: string;
	item_id?: string;
	item_list_name?: string;
	item_name?: string;
	item_variant?: string;
	item_list_id?: string;
	location_id?: string;
	price?: string;
	quantity?: number /* float64 */;
}

//////////
// source: login.go

export interface Login {
	method?: string;
}

//////////
// source: search.go

export interface Search {
	search_term?: string;
}

//////////
// source: signup.go

export interface SignUp {
	method?: string;
}
